// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBclumxc3cJfXnGAaWyTE4iKnyxzTPLqUo',
    appId: '1:894763906889:web:ddd1a39869906995ba4c98',
    messagingSenderId: '894763906889',
    projectId: 'food-app-247cc',
    authDomain: 'food-app-247cc.firebaseapp.com',
    storageBucket: 'food-app-247cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu6OOB25i7_QsKO8Aa4sGzq3p4wwwwumc',
    appId: '1:894763906889:android:dec6aea8a0c1639eba4c98',
    messagingSenderId: '894763906889',
    projectId: 'food-app-247cc',
    storageBucket: 'food-app-247cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU3u9K-XwHXqymL_pLSDmZX0kBjz-G5Io',
    appId: '1:894763906889:ios:1a374b8eb2c40034ba4c98',
    messagingSenderId: '894763906889',
    projectId: 'food-app-247cc',
    storageBucket: 'food-app-247cc.firebasestorage.app',
    iosBundleId: 'com.example.appFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU3u9K-XwHXqymL_pLSDmZX0kBjz-G5Io',
    appId: '1:894763906889:ios:1a374b8eb2c40034ba4c98',
    messagingSenderId: '894763906889',
    projectId: 'food-app-247cc',
    storageBucket: 'food-app-247cc.firebasestorage.app',
    iosBundleId: 'com.example.appFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBclumxc3cJfXnGAaWyTE4iKnyxzTPLqUo',
    appId: '1:894763906889:web:1bb77f0b03e2a658ba4c98',
    messagingSenderId: '894763906889',
    projectId: 'food-app-247cc',
    authDomain: 'food-app-247cc.firebaseapp.com',
    storageBucket: 'food-app-247cc.firebasestorage.app',
  );
}
